### ISSUE TITLE
Arbeitsteilung und erstes Klassendiagramm

### ISSUE THREAD

**Issue by EliasTechnik** [EliasTechnik/PruefungsleistungEliasVincent#1]
![Klassendiagram Skizze 1](https://user-images.githubusercontent.com/83211893/126492749-eedd862a-c0af-4585-a776-0fc921e6e6e5.png)

Nach unserem Meeting heute Vormittag habe ich diese Skizze eines Klassendiagramms angefertigt. Es erhebt keinen Anspruch auf Vollständigkeit aber verdeutlicht die Arbeitsteilung und grobe Struktur des Projektes.

Die Anwendung teilt sich aktuell in zwei Hauptbestandteile. Zum einen das eigentliche Spiel und alles was zu dessen Funktion gehört und zum anderen QLearning. Letzteres werden wir nutzen um ein Modell zu trainieren welches in der Lage ist das Spiel zu spielen. Die Verwendung von ML.Net ist aktuell noch nicht geplant da es sich nicht für den Anwendungszweck eignet und schwer in Unity zu integrieren ist.

Die Arbeitsteilung gestaltet sich vorerst wie folgt: 
- Vincent kümmert sich um die Entwicklung des Spiels nach oben gegebener Struktur. Dabei kann sich an dem Testprojekt orientiert werden: [Testprojekt](https://github.com/EliasTechnik/UnityMLNet/tree/QLearning)
- Elias implementiert die QLearning Klasse nach unseren heutigen Überlegungen und so modular wie möglich.

Der der eher freie Kapazitäten hat hilft den anderen bei der Implementierung.

**Comment by Spidervini** [comment]
Wie wollen wir die Bewertung der Aktionen der KI mittels einer Scoring Klasse implementieren? Es wäre empfehlenswert den Spieler und seine Bewegungen möglichst getrennt von der Bewertungslogik umzusetzen.

**Comment by EliasTechnik** [comment]
Ja, möglichst getrennt. Das schafft später mehr Möglichkeiten falls wir das Scoring ausbauen.
