### ISSUE TITLE
UI Setup

### ISSUE THREAD

**Issue by Spidervini** [EliasTechnik/PruefungsleistungEliasVincent#4]
Die UI hat ihr erstes Overlay erhalten. Es wird angezeigt wie viel Runden seit dem Start des Spiels vergangen sind (neue Runden beginnen nach dem Erreichen des Ziels). Ebenfalls gibt die UI an, wie lange die laufende Runde dauert und welche durchschnittliche Zeit die bisherigen Runden benötigt haben. Weitere Vorschläge für zusätzliche Informationen sind erwünscht.

**Comment by EliasTechnik** [comment]
Sofern noch freie Kapazitäten sind wäre es gut wenn schon Buttons zum steuern des Trainings und des Spiels vorhanden sind. Ich denke da an Buttons für:

- KI laden
- neue KI erstellen/trainieren
- Training fortsetzen/pausieren
- Score zurücksetzen

**Comment by Spidervini** [comment]
Bei Gelegenheit werden zusätzliche Features noch hinzugefügt.
