### ISSUE TITLE
Zusammenführung von QLearning und Unity Branch

### ISSUE THREAD

**Issue by EliasTechnik** [EliasTechnik/PruefungsleistungEliasVincent#5]
Alle notwendigen bestandteile der für das QLearning sind inzwischen implementiert. Damit die Zusammenführung funktioniert muss jeder folgende Dinge dokumentieren:

**Elias:**

- Wie baut (instanziiert) man das Modell korrekt?
- Welche Schnittstellen gibt es und wie werden sie verwendet? (Vorrangig Input/Output)
- Welche Funktionen erfüllen die einzelnen Klassen?
- Wie übergibt man Eingaben an das Modell?
- In welchen Format liegen die Vorhersagen vor?

**Vincent**

- Welche Klassen gibt es und welche Funktionen erfüllen sie?
- An welcher Stelle im Code sollen die Input Daten an die KI übergeben werden?
- An welcher Stelle soll die Vorhersage der KI verarbeitet werden?
- Was gibt es für Eingangsdaten?

Ich werde heute Nachmittag meinen Teil dokumentieren. Sobald du deinen Teil dokumentiert hast können wir beide Branches zusammenführen.

**Comment by Spidervini** [comment]
Zum Mergen beendet jeder seine noch anstehenden Aufgaben. 
Vincent: Hinzufügen weiterer Raycasts, um Entfernung zu Hindernissen zuverlässiger erfassen zu können.
Elias: Abschließende Features für die AI Skripte
Zuerst wird der Branch "QLearning" und darauf folgend "Unity" gemerged, um eventuelle Komplikationen zu vermeiden.

**Comment by EliasTechnik** [comment]
Als nächstes steht die Integration im Spiel an. Siehe dazu folgendes Issue [Integration von QAgent im Spiel #9](https://github.com/EliasTechnik/PruefungsleistungEliasVincent/issues/9)

**Comment by EliasTechnik** [comment]
Dieses Issue ist damit geschlossen.
